drop extension if exists "pg_net";


  create table "public"."receipts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date,
    "store" text default ''::text,
    "location" text default ''::text,
    "gluten_total" double precision,
    "receipt_total" double precision,
    "items" json,
    "image_link" text default ''::text
      );


alter table "public"."receipts" enable row level security;

CREATE UNIQUE INDEX receipts_pkey ON public.receipts USING btree (id);

alter table "public"."receipts" add constraint "receipts_pkey" PRIMARY KEY using index "receipts_pkey";

grant delete on table "public"."receipts" to "anon";

grant insert on table "public"."receipts" to "anon";

grant references on table "public"."receipts" to "anon";

grant select on table "public"."receipts" to "anon";

grant trigger on table "public"."receipts" to "anon";

grant truncate on table "public"."receipts" to "anon";

grant update on table "public"."receipts" to "anon";

grant delete on table "public"."receipts" to "authenticated";

grant insert on table "public"."receipts" to "authenticated";

grant references on table "public"."receipts" to "authenticated";

grant select on table "public"."receipts" to "authenticated";

grant trigger on table "public"."receipts" to "authenticated";

grant truncate on table "public"."receipts" to "authenticated";

grant update on table "public"."receipts" to "authenticated";

grant delete on table "public"."receipts" to "service_role";

grant insert on table "public"."receipts" to "service_role";

grant references on table "public"."receipts" to "service_role";

grant select on table "public"."receipts" to "service_role";

grant trigger on table "public"."receipts" to "service_role";

grant truncate on table "public"."receipts" to "service_role";

grant update on table "public"."receipts" to "service_role";


  create policy "Enable delete for users based on user_id"
  on "public"."receipts"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."receipts"
  as permissive
  for select
  to public
using (true);



  create policy "insert"
  on "public"."receipts"
  as permissive
  for insert
  to public
with check (true);



  create policy "Get Scans 1t1ml2_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'scans'::text));



  create policy "Get Scans 1t1ml2_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'scans'::text));



  create policy "Get Scans 1t1ml2_2"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'scans'::text));



