/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as DashboardRouteImport } from './routes/dashboard'

const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/receipts': typeof ReceiptsRoute
  '/scans': typeof ScansRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/receipts': typeof ReceiptsRoute
  '/scans': typeof ScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRoute
  '/receipts': typeof ReceiptsRoute
  '/scans': typeof ScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/receipts' | '/scans'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/receipts' | '/scans'
  id: '__root__' | '/dashboard' | '/receipts' | '/scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ScansRoute: typeof ScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  ReceiptsRoute: ReceiptsRoute,
  ScansRoute: ScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
